PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX inst: <http://www.ontotext.com/connectors/lucene/instance#>
PREFIX : <http://www.ontotext.com/connectors/lucene#>

select ?ingredients ?recipe ?name ?recYield ?recImage ?totalTime
where {
    graph <https://broker.semantify.it/graph/Or1IAoO73z/WrJWA3u72z/latest>{
    ?s schema:recipeInstructions ?recipe;
       schema:ingredients ?ingredients;
       schema:name ?name;
       schema:totalTime ?totalTime;
       OPTIONAL{?s schema:recipeYield ?recYield}
       OPTIONAL{?s schema:image ?recImage}
    {select ?s where {
    graph <https://broker.semantify.it/graph/Or1IAoO73z/WrJWA3u72z/latest> {
        ?search a inst:recipeConn ;
        :query "{ingredients}" ;
        :entities ?s.
        ?s a schema:Recipe.
        ?s schema:interactionCount ?icount   
    }
}
order by desc(xsd:integer(?realCount))

limit 5
offset 0
    }
   }
    FILTER(!strStarts(?recipe,"Tipp"))
}